services:
  app_blue:
    image: ${BLUE_IMAGE}  # Will pull from registry
    container_name: app_blue
    environment:
      - PORT=${PORT:-3000}
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
    ports:
      - "${BLUE_PORT:-8081}:${PORT:-3000}"
    networks:
      - app_network
    restart: unless-stopped

  app_green:
    image: ${GREEN_IMAGE}  # Will pull from registry
    container_name: app_green
    environment:
      - PORT=${PORT:-3000}
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
    ports:
      - "${GREEN_PORT:-8082}:${PORT:-3000}"
    networks:
      - app_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "${NGINX_PORT:-8080}:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf:ro
    networks:
      - app_network
    depends_on:
      - app_blue
      - app_green
    restart: unless-stopped

networks:
  app_network:
    driver: bridge