services:
  app_blue:
    build:
      context: ./app
    container_name: app_blue
    environment:
      - PORT=3000
      - APP_POOL=blue
      - RELEASE_ID=blue-v1.0.0
    ports:
      - "8081:3000"
    networks:
      - app_network
    restart: unless-stopped

  app_green:
    build:
      context: ./app
    container_name: app_green
    environment:
      - PORT=3000
      - APP_POOL=green
      - RELEASE_ID=green-v1.0.0
    ports:
      - "8082:3000"
    networks:
      - app_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf:ro
    networks:
      - app_network
    depends_on:
      - app_blue
      - app_green
    restart: unless-stopped

networks:
  app_network:
    driver: bridge